version: "3.8"
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    network_mode: "host"

volumes:
  dbdata: