"""initial migrations

Revision ID: 1beadfbb74b3
Revises: 
Create Date: 2020-04-26 20:24:37.272250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beadfbb74b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_listened_date', sa.Date(), nullable=True),
    sa.Column('listen_reps', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playback')
    op.drop_table('track')
    # ### end Alembic commands ###
